import { Icon } from '@iconify/react';
import { Link, usePage } from '@inertiajs/react';
import { navigation } from '../../../data/demo/navigation';
import { routes } from '../../../config/routes';
const groups=[['accueil','annonces'],['travail','logement','vehicules','evenements','guide','communaute','messages'],['recherches','favoris','mes_annonces']];
export default function Sidebar({isMobileOpen=false,onMobileClose}){
 const {url}=usePage();
 const content=<aside className="flex h-dvh w-[260px] shrink-0 flex-col border-r border-[#E4E9F2] bg-white">
  <div className="flex h-20 shrink-0 items-center justify-between px-5"><Link href={routes.dashboard} onClick={onMobileClose} className="flex items-center gap-3"><span className="relative grid h-12 w-12 place-items-center"><img src="/images/logovav.png" alt="" className="absolute w-[115px] max-w-none"/></span><span className="text-xl font-extrabold">Kangoust</span></Link><button onClick={onMobileClose} aria-label="Fermer le menu" className="grid h-9 w-9 place-items-center lg:hidden"><Icon icon="solar:close-circle-broken" className="h-6 w-6"/></button></div>
  <div className="flex-1 space-y-6 overflow-y-auto px-3 py-5">{groups.map((ids,index)=><nav key={index} className="space-y-1" aria-label={['Navigation principale','Découvrir','Outils'][index]}>{ids.map(id=>{const item=navigation.find(n=>n.id===id);const active=url===item.href||url.startsWith(item.href+'/');return <Link key={id} href={item.href} onClick={onMobileClose} className={`relative flex min-h-11 items-center gap-3 rounded-lg px-3.5 text-sm font-semibold transition ${active?'bg-[#EAF1FF] text-[#2F67D8]':'text-[#334155] hover:bg-[#F5F8FF]'}`}><Icon icon={item.icon} className="h-5 w-5 shrink-0"/><span className="min-w-0 flex-1 truncate">{item.label}</span>{item.badge&&<span className="rounded bg-[#F1F5F9] px-1.5 py-0.5 text-[10px] font-bold text-[#64718F]">{item.badge}</span>}{active&&<span className="absolute inset-y-1 right-0 w-0.5 rounded bg-[#2F67D8]"/>}</Link>})}</nav>)}
   <div className="rounded-2xl bg-gradient-to-br from-[#2F67D8] to-[#10245E] p-4 text-white"><div className="flex items-center gap-2 font-extrabold"><Icon icon="solar:document-add-broken" className="h-5 w-5"/>Kangoust CV</div><p className="mt-3 text-xs leading-5 text-blue-100">Créez votre CV australien avec notre système d’analyse intelligent.</p><Link href={routes.cv} onClick={onMobileClose} className="mt-4 block rounded-lg bg-white px-3 py-2 text-center text-xs font-bold text-[#10245E]">Créer mon CV</Link></div>
  </div></aside>;
 return <><div className="hidden shrink-0 lg:block">{content}</div>{isMobileOpen&&<div className="fixed inset-0 z-50 flex lg:hidden"><button className="absolute inset-0 bg-[#10245E]/40" onClick={onMobileClose} aria-label="Fermer le menu"/><div className="relative">{content}</div></div>}</>
}
