import { Icon } from '@iconify/react';
import { Link, router } from '@inertiajs/react';
import { useEffect, useRef, useState } from 'react';
import { currentUser } from '../../../data/demo/currentUser';
import { routes } from '../../../config/routes';
export default function Header({ userName=currentUser.displayName,userAvatar=currentUser.avatar,onMobileMenuOpen,searchMode='full' }){
 const [open,setOpen]=useState(false); const ref=useRef(null);
 useEffect(()=>{const close=e=>!ref.current?.contains(e.target)&&setOpen(false); document.addEventListener('mousedown',close); return()=>document.removeEventListener('mousedown',close)},[]);
 return <header className="z-30 flex h-16 shrink-0 items-center gap-3 border-b border-[#E4E9F2] bg-white px-4 sm:h-20 sm:px-6 lg:px-8">
  <button type="button" onClick={onMobileMenuOpen} aria-label="Ouvrir le menu" className="grid h-10 w-10 place-items-center rounded-lg border border-[#E4E9F2] text-[#10245E] lg:hidden"><Icon icon="solar:hamburger-menu-broken" className="h-6 w-6"/></button>
  {searchMode!=='hidden'&&<form onSubmit={e=>{e.preventDefault(); router.get(routes.listings,{search:e.currentTarget.search.value},{preserveState:true})}} className={`${searchMode==='compact'?'max-w-sm':'max-w-xl'} hidden min-w-0 flex-1 sm:block`}><label className="relative block"><span className="sr-only">Rechercher</span><Icon icon="solar:magnifer-broken" className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#64718F]"/><input name="search" placeholder="Rechercher un logement, un emploi, un guide..." className="h-11 w-full rounded-full border border-[#D9E1EE] bg-white pl-12 pr-4 text-sm text-[#10245E] outline-none focus:border-[#2F67D8] focus:ring-2 focus:ring-[#EAF1FF]"/></label></form>}
  <div className="ml-auto flex items-center gap-1 sm:gap-2">
   <Link href={routes.publish} className="hidden h-10 items-center gap-2 rounded-lg px-3 text-sm font-bold text-[#10245E] hover:bg-[#F5F8FF] md:flex"><Icon icon="solar:add-circle-broken" className="h-5 w-5"/>Publier</Link>
   <Link href={routes.notifications} aria-label="Notifications" className="relative grid h-10 w-10 place-items-center rounded-full hover:bg-[#F5F8FF]"><Icon icon="solar:bell-broken" className="h-5 w-5"/><span className="absolute right-1 top-0 rounded-full bg-red-500 px-1 text-[9px] font-bold text-white">{currentUser.unreadNotifications}</span></Link>
   <Link href={routes.messages} aria-label="Messages" className="relative grid h-10 w-10 place-items-center rounded-full hover:bg-[#F5F8FF]"><Icon icon="solar:chat-round-dots-broken" className="h-5 w-5"/><span className="absolute right-0 top-0 rounded-full bg-red-500 px-1 text-[9px] font-bold text-white">{currentUser.unreadMessages}</span></Link>
   <div className="relative" ref={ref}><button onClick={()=>setOpen(!open)} aria-expanded={open} className="flex items-center gap-2 rounded-full p-1 hover:bg-[#F5F8FF]"><img src={userAvatar} alt="" className="h-10 w-10 rounded-full object-cover"/><span className="hidden text-sm font-bold md:block">{userName}</span><Icon icon="solar:alt-arrow-down-broken" className="hidden h-4 w-4 md:block"/></button>{open&&<div className="absolute right-0 mt-2 w-56 rounded-xl border border-[#E4E9F2] bg-white p-2 shadow-xl"><Link href={routes.profile} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-[#F5F8FF]"><Icon icon="solar:user-broken" className="h-5 w-5"/>Mon profil</Link><Link href={routes.settings} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-[#F5F8FF]"><Icon icon="solar:settings-broken" className="h-5 w-5"/>Paramètres</Link><Link href="/login" className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-red-600 hover:bg-red-50"><Icon icon="solar:logout-2-broken" className="h-5 w-5"/>Se déconnecter</Link></div>}</div>
  </div>
 </header>
}
